### PR TITLE
Issue #125

### LINKED ISSUE #125: accessibility: <html> element does not have a [lang] attribute
According to this [audit report from Chrome Dev Tools](https://github.com/codeforsanjose/census2020/files/4054578/Census2020-Audit-Report-0122020.pdf), this can be enhanced to improve accessibility:

If a page doesn't specify a lang attribute, a screen reader assumes that the page is in the default language that the user chose when setting up the screen reader. If the page isn't actually in the default language, then the screen reader might not announce the page's text correctly. Learn more. https://web.dev/html-has-lang/?utm_source=lighthouse&utm_medium=devtools

Failing Elements
--
`html<html>`

### PR DESCRIPTION
**Pull request by danekolsen**
Added default en lang attribute to html tag and line 23 to App.js which changes the lang attribute when the user switches languages.

Fixes #125

### CODE REVIEW

**Comment by ychoy** [comment]
This looks good to me. I added the PR description to include "Fixes #125" so when this gets merged, it will close the issue.

@danekolsen,  is it necessary to include `package-lock.json` commit in this PR? My understanding is that it's easier to avoid merge conflicts if we don't touch `package-lock.json` file, and only update `package.json` file and make commits regarding the latter file.

**Review by ychoy — APPROVED** [review]

File: client/components/SampleCensus.js [hunk 1]
```diff
@@ -528,7 +528,7 @@ const sampleCensusButtons = [
     button: 'components.SampleCensus.preliminary_button',
     description: 'components.SampleCensus.preliminary_description',
     questions: PRELIMINARY_QUESTIONS,
-    icon: '',
+    icon: ''
```
Comment (JMStudiosJoe) [inline client/components/SampleCensus.js:531]: just a note, I prefer to leave the trailing commas in so that if new change comes here it does look as confusing but this is only for git pr reviewing.

**Review by JMStudiosJoe — APPROVED** [review]
